### ISSUE TITLE
Automated e2e tests

### ISSUE THREAD

**Issue by martijn-gv** [martijnvdbrug/shops#57]
Run Vendure backend locally connecting to test
Run storefront-dev-server connecting to local Vendure instance
Use nightwatch.js to place an order

**Comment by martijnvdbrug** [comment]
Made first example e2e for ordering via the deployed dev env

**Comment by martijnvdbrug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Als een klant een cadeau kiest, wordt er geen buitenlandse BTW meer berekend](https://trello.com/c/PHe4POLa/379-als-een-klant-een-cadeau-kiest-wordt-er-geen-buitenlandse-btw-meer-berekend)
